### PR TITLE
Support Webpack 5

### PR DESCRIPTION
**Pull request by ianwalter**
This PR contains a:

- [ ] **bugfix**
- [x] new **feature**
- [x] **code refactor**
- [x] **test update** 
- [ ] **typo fix**
- [ ] **metadata update**

### Motivation / Use-Case

I ran into a few issues trying to upgrade a project using webpack-hot-client to Webpack 5. This should hopefully provide a "next" version that will work.

### Breaking Changes

Webpack 5 is a breaking change but I'm not aware of anything that needs to change in the usage of this module outside of:
https://webpack.js.org/migrate/5/

### Additional Info

I didn't realize there was already a `next` branch so there are a bunch of changes carried over from master. Let me know if there should be anything done about this.

### CODE REVIEW

**Comment by shellscape** [comment]
Thanks for opening this. I'll carve out some time tomorrow to go through it.

**Comment by shellscape** [comment]
Whew I let this one drop between the couch cushions. Sorry about that. Does this need any updates since July?

**Comment by neroneroffy** [comment]
> Whew I let this one drop between the couch cushions. Sorry about that. Does this need any updates since July?

I 'm appreciate if you merge this pr and release a new version, because our project was upgrade to webpack v5, and rely on webpack-hot-client, but webpack-hot-client dosen't support webpack v5

**Comment by shellscape** [comment]
thanks!

**Comment by charlessuh** [comment]
> > Whew I let this one drop between the couch cushions. Sorry about that. Does this need any updates since July?
> 
> I 'm appreciate if you merge this pr and release a new version, because our project was upgrade to webpack v5, and rely on webpack-hot-client, but webpack-hot-client dosen't support webpack v5

@shellscape: +1 Could you release a new version of this package on npm with this PR and an updated `peerDependency` in package.json? 

https://github.com/shellscape/webpack-hot-client/blob/e5fa27f238252074cb812ab210a7b6c63cfd757a/package.json#L45-L47

**Comment by charlessuh** [comment]
@ianwalter: Would it be possible for you to open this PR against master?

**Pull request merged**
